### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shaonturaj** [Widiskel/not-pixel-bot#11]
![Screenshot_20241011_224124_Termius](https://github.com/user-attachments/assets/f46bec3c-3d9c-4f22-9e69-a8fc78e2c933)
![Screenshot_20241011_224118_Termius](https://github.com/user-attachments/assets/5b6d7b6e-30e2-4c30-8877-f23040a6b357)
![Screenshot_20241011_224220_Termius](https://github.com/user-attachments/assets/2fe73ed0-e17b-45fa-8140-952bda59a7dd)

Shows all there status but never used a single energy to Paint. Why this happening?  Is there anything i am missing?

**Comment by Widiskel** [comment]
try to play manual first, and. re create your session
