### ISSUE TITLE
How do I change the selected template?

### ISSUE THREAD

**Issue by nikita-vedrov** [Widiskel/not-pixel-bot#14]
Every time I ran the bot, it would select “Pumpkin” and try to to paint over the pixel. The problem is that I get 0 points for all these actions. So how do I change the template to another one (including the global template)? I tried to find it in the documentation and dig through the code, but I didn't find anything.

**Comment by copycatcodex** [comment]
edit the latest config contained in the config/config.js folder.

If you have finished editing but still get the "pumpkin" error, copy the config file into app/config

The latest config should look like this
![image](https://github.com/user-attachments/assets/f4b342a6-73b9-4310-afcd-aaf9824710f7)

**Comment by nikita-vedrov** [comment]
Yes, thanks, I've already noticed this update. The only thing I don't understand is where to get the template id?

**Comment by Widiskel** [comment]
pull , and join tele you can see the video tutorial there
