### ISSUE TITLE
Stuck on Searching on Area 1...

### ISSUE THREAD

**Issue by b4uheart** [Widiskel/not-pixel-bot#7]
From this new update it's stucks in searching here is log
================= Account 7426036186 =============
Name         : Rahuk
Balance      : 304.67549033333705
Charge       : 1

Status : Searching on Area 1...
Delay : Delaying for 0 Hours 0 Minutes 0 Seconds
==============================================
⠼

**Comment by Widiskel** [comment]
pull and start again, im forgot to add reauthentication when failed
